### ISSUE TITLE
do not prevent v8 optimizing of promisified functions

### ISSUE THREAD

**Issue by schnittstabil** [SamVerschueren/rfpify#1]
Same as discussed at sindresorhus/pify#11.

**Comment by SamVerschueren** [comment]
Thanks :+1:

**Comment by SamVerschueren** [comment]
Fixed in `v1.0.0`

**Comment by schnittstabil** [comment]
Thanks. I do not know if you already knew, but it is possible to [close issues via commit messages](https://help.github.com/articles/closing-issues-via-commit-messages/).

**Comment by SamVerschueren** [comment]
Yes I know, but I just forgot :).
